
import { useEffect, useState } from "react";
import { storage } from "@/lib/storage";
import { AuditLog as AuditLogType } from "@/types/inventory";
import { PDFDownloadLink } from '@react-pdf/renderer';
import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Download, Printer, Share2 } from "lucide-react";
import { toast } from "sonner";

// PDF styles for the audit report
const styles = StyleSheet.create({
  page: { padding: 30, fontSize: 12 },
  header: { marginBottom: 20 },
  title: { fontSize: 20, marginBottom: 10 },
  table: { width: '100%' },
  tableRow: { flexDirection: 'row', borderBottomWidth: 1, borderColor: '#000', padding: 8 },
  tableHeader: { backgroundColor: '#f3f4f6' },
  tableCell: { flex: 1 },
  footer: { position: 'absolute', bottom: 30, left: 30, right: 30, textAlign: 'center', fontSize: 10 },
});

// PDF Report Component
const AuditReportPDF = ({ logs, dateRange }: { logs: AuditLogType[], dateRange: string }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>Audit Log Report</Text>
        <Text>Generated on: {new Date().toLocaleString()}</Text>
        <Text>Period: {dateRange}</Text>
      </View>

      <View style={styles.table}>
        <View style={[styles.tableRow, styles.tableHeader]}>
          <Text style={styles.tableCell}>Date</Text>
          <Text style={styles.tableCell}>Action</Text>
          <Text style={styles.tableCell}>User</Text>
          <Text style={styles.tableCell}>Details</Text>
        </View>
        {logs.map((log, index) => (
          <View key={index} style={styles.tableRow}>
            <Text style={styles.tableCell}>{new Date(log.date).toLocaleString()}</Text>
            <Text style={styles.tableCell}>{log.action}</Text>
            <Text style={styles.tableCell}>
              {storage.getUsers().find(u => u.id === log.userId)?.username || 'Unknown'}
            </Text>
            <Text style={styles.tableCell}>{log.details}</Text>
          </View>
        ))}
      </View>

      <Text style={styles.footer}>
        Report generated by Inventory Management System
      </Text>
    </Page>
  </Document>
);

export function AuditLog() {
  const [logs, setLogs] = useState<AuditLogType[]>([]);
  const [filteredLogs, setFilteredLogs] = useState<AuditLogType[]>([]);

  useEffect(() => {
    loadAuditLogs();
  }, []);

  const loadAuditLogs = () => {
    const auditLogs = storage.getAuditLogs();
    const sortedLogs = auditLogs.sort((a, b) => 
      new Date(b.date).getTime() - new Date(a.date).getTime()
    );
    setLogs(sortedLogs);
    setFilteredLogs(sortedLogs);
  };

  const formatDate = (date: string) => {
    return new Date(date).toLocaleString();
  };

  const handleShare = async () => {
    try {
      const data = JSON.stringify(logs, null, 2);
      const blob = new Blob([data], { type: 'application/json' });
      
      if (navigator.share) {
        const file = new File([blob], 'audit-log.json', { type: 'application/json' });
        await navigator.share({
          files: [file],
          title: 'Audit Log Report',
          text: 'Inventory Management System Audit Log'
        });
      } else {
        // Fallback to download if Web Share API is not available
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'audit-log.json';
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
      }
      toast.success('Audit log exported successfully');
    } catch (error) {
      toast.error('Failed to share audit log');
      console.error('Error sharing audit log:', error);
    }
  };

  return (
    <Card className="w-full">
      <CardHeader className="flex flex-row items-center justify-between">
        <CardTitle>Audit Log</CardTitle>
        <div className="flex gap-2">
          <PDFDownloadLink
            document={
              <AuditReportPDF 
                logs={filteredLogs} 
                dateRange={`${formatDate(filteredLogs[filteredLogs.length - 1]?.date)} - ${formatDate(filteredLogs[0]?.date)}`}
              />
            }
            fileName={`audit-report-${new Date().toISOString().slice(0, 10)}.pdf`}
          >
            {({ loading }) => (
              <Button variant="outline" disabled={loading}>
                <Printer className="h-4 w-4 mr-2" />
                Print Report
              </Button>
            )}
          </PDFDownloadLink>
          <Button variant="outline" onClick={handleShare}>
            <Share2 className="h-4 w-4 mr-2" />
            Share
          </Button>
          <Button variant="outline" onClick={() => loadAuditLogs()}>
            <Download className="h-4 w-4 mr-2" />
            Refresh
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Date</TableHead>
              <TableHead>Action</TableHead>
              <TableHead>User</TableHead>
              <TableHead>Details</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {filteredLogs.map((log) => {
              const user = storage.getUsers().find(u => u.id === log.userId);
              return (
                <TableRow key={log.id}>
                  <TableCell>{formatDate(log.date)}</TableCell>
                  <TableCell className="capitalize">{log.action}</TableCell>
                  <TableCell>{user?.username || 'Unknown'}</TableCell>
                  <TableCell>{log.details}</TableCell>
                </TableRow>
              );
            })}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  );
}
