import { storage } from "@/lib/storage";
import { InventoryItem, Vendor, Customer, Sale } from "@/types/inventory";

export const seedSampleData = () => {
  // Check if sample data already exists
  const existingProducts = storage.getInventoryItems();
  const existingVendors = storage.getVendors();
  const existingCustomers = storage.getCustomers();

  if (existingProducts.length > 0 || existingVendors.length > 0 || existingCustomers.length > 0) {
    console.log("Sample data already exists, skipping seeding");
    return;
  }

  // Sample Vendors
  const sampleVendors: Vendor[] = [
    {
      id: crypto.randomUUID(),
      name: "Tech Solutions Ltd",
      email: "contact@techsolutions.com",
      phone: "+1-555-0101",
      address: "123 Technology Ave, Silicon Valley, CA 94000",
      notes: "Primary electronics supplier",
      type: "manufacturer",
      products: ["electronics", "accessories"],
      paymentTerms: "Net 30",
      taxId: "TS123456789",
      rating: 4.8,
      activeContract: true,
    },
    {
      id: crypto.randomUUID(),
      name: "Office Supplies Pro",
      email: "sales@officesuppliespro.com",
      phone: "+1-555-0202",
      address: "456 Business Blvd, New York, NY 10001",
      notes: "Office furniture and supplies",
      type: "wholesaler",
      products: ["furniture", "office-supplies"],
      paymentTerms: "Net 15",
      taxId: "OSP987654321",
      rating: 4.5,
      activeContract: true,
    },
    {
      id: crypto.randomUUID(),
      name: "Global Electronics",
      email: "info@globalelectronics.com",
      phone: "+1-555-0303",
      address: "789 International Dr, Miami, FL 33101",
      notes: "Consumer electronics distributor",
      type: "distributor",
      products: ["electronics", "consumer-goods"],
      paymentTerms: "Net 45",
      taxId: "GE456789123",
      rating: 4.2,
      activeContract: false,
    },
  ];

  // Sample Customers
  const sampleCustomers: Customer[] = [
    {
      id: crypto.randomUUID(),
      name: "Acme Corporation",
      email: "purchasing@acmecorp.com",
      phone: "+1-555-1001",
      address: "100 Corporate Plaza, Boston, MA 02101",
      type: "business",
      taxId: "123456789",
      creditLimit: 50000,
      notes: "Large corporate client",
      createdAt: new Date().toISOString(),
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "John Smith",
      email: "john.smith@email.com",
      phone: "+1-555-1002",
      address: "456 Residential St, Chicago, IL 60601",
      type: "individual",
      creditLimit: 5000,
      notes: "Regular retail customer",
      createdAt: new Date().toISOString(),
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "StartUp Innovations",
      email: "orders@startupinnovations.com",
      phone: "+1-555-1003",
      address: "789 Startup Lane, Austin, TX 73301",
      type: "business",
      taxId: "987654321",
      creditLimit: 25000,
      notes: "Tech startup, growing client",
      createdAt: new Date().toISOString(),
      lastUpdated: new Date().toISOString(),
    },
  ];

  // Sample Plumbing Store Products
  const sampleProducts: InventoryItem[] = [
    {
      id: crypto.randomUUID(),
      name: "PVC Pipe 4 inch",
      description: "High-quality PVC pipe for drainage and plumbing systems",
      category: "Pipes",
      quantity: 150,
      minQuantity: 25,
      cost: 45.50,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Copper Fitting Elbow 90°",
      description: "90-degree copper elbow fitting for water supply lines",
      category: "Fittings",
      quantity: 200,
      minQuantity: 40,
      cost: 12.75,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Ball Valve 1 inch",
      description: "Heavy-duty brass ball valve with lever handle",
      category: "Valves",
      quantity: 80,
      minQuantity: 15,
      cost: 89.99,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Toilet Flapper Kit",
      description: "Universal toilet flapper replacement kit",
      category: "Toilet Parts",
      quantity: 65,
      minQuantity: 10,
      cost: 15.25,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Kitchen Sink Faucet",
      description: "Stainless steel kitchen faucet with pull-down sprayer",
      category: "Faucets",
      quantity: 35,
      minQuantity: 8,
      cost: 185.00,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Pipe Wrench 14 inch",
      description: "Heavy-duty pipe wrench for plumbing repairs",
      category: "Tools",
      quantity: 25,
      minQuantity: 5,
      cost: 65.75,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Water Heater Element",
      description: "Electric water heater heating element 4500W",
      category: "Water Heater Parts",
      quantity: 45,
      minQuantity: 8,
      cost: 45.99,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Shower Head Chrome",
      description: "Chrome finish rain shower head with multiple settings",
      category: "Shower Parts",
      quantity: 55,
      minQuantity: 12,
      cost: 78.50,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "PEX Tubing 1/2 inch",
      description: "Cross-linked polyethylene tubing for plumbing",
      category: "Pipes",
      quantity: 300,
      minQuantity: 50,
      cost: 2.25,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Drain Snake 25 ft",
      description: "Flexible drain cleaning snake for clogs",
      category: "Tools",
      quantity: 20,
      minQuantity: 4,
      cost: 35.99,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Bathroom Sink P-Trap",
      description: "Chrome plated P-trap for bathroom sinks",
      category: "Drain Parts",
      quantity: 75,
      minQuantity: 15,
      cost: 28.75,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Garbage Disposal Unit",
      description: "1/2 HP garbage disposal with sound insulation",
      category: "Appliances",
      quantity: 18,
      minQuantity: 3,
      cost: 125.00,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Toilet Wax Ring",
      description: "Wax ring seal for toilet installation",
      category: "Toilet Parts",
      quantity: 100,
      minQuantity: 20,
      cost: 8.50,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Pipe Joint Compound",
      description: "Thread sealing compound for pipe joints",
      category: "Supplies",
      quantity: 85,
      minQuantity: 15,
      cost: 12.99,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Bathtub Drain Stopper",
      description: "Universal bathtub drain stopper assembly",
      category: "Drain Parts",
      quantity: 40,
      minQuantity: 8,
      cost: 22.50,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Water Filter Cartridge",
      description: "Replacement water filter cartridge for whole house systems",
      category: "Filters",
      quantity: 60,
      minQuantity: 12,
      cost: 38.99,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Copper Pipe 3/4 inch",
      description: "Type L copper pipe for water supply lines",
      category: "Pipes",
      quantity: 120,
      minQuantity: 20,
      cost: 8.75,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Plumber's Putty",
      description: "Waterproof putty for sealing plumbing fixtures",
      category: "Supplies",
      quantity: 95,
      minQuantity: 18,
      cost: 6.99,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Sump Pump 1/3 HP",
      description: "Submersible sump pump for basement drainage",
      category: "Pumps",
      quantity: 12,
      minQuantity: 2,
      cost: 189.99,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Shut-off Valve 1/2 inch",
      description: "Quarter-turn shut-off valve for water supply",
      category: "Valves",
      quantity: 110,
      minQuantity: 25,
      cost: 18.50,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Flexible Supply Line",
      description: "Braided stainless steel supply line 18 inch",
      category: "Supply Lines",
      quantity: 85,
      minQuantity: 20,
      cost: 14.25,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Pipe Cutter Tool",
      description: "Ratcheting pipe cutter for copper and plastic pipes",
      category: "Tools",
      quantity: 15,
      minQuantity: 3,
      cost: 45.75,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Water Pressure Regulator",
      description: "Adjustable water pressure reducing valve",
      category: "Valves",
      quantity: 28,
      minQuantity: 6,
      cost: 78.99,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Shower Valve Cartridge",
      description: "Replacement cartridge for single handle shower valves",
      category: "Shower Parts",
      quantity: 50,
      minQuantity: 10,
      cost: 35.50,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Toilet Fill Valve",
      description: "Universal toilet fill valve with adjustable height",
      category: "Toilet Parts",
      quantity: 70,
      minQuantity: 15,
      cost: 25.99,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Pipe Insulation Foam",
      description: "Foam pipe insulation for preventing freezing",
      category: "Supplies",
      quantity: 200,
      minQuantity: 40,
      cost: 3.75,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Basin Wrench",
      description: "Long-reach basin wrench for tight spaces",
      category: "Tools",
      quantity: 10,
      minQuantity: 2,
      cost: 55.25,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Backflow Preventer",
      description: "Testable backflow prevention device",
      category: "Safety Equipment",
      quantity: 15,
      minQuantity: 3,
      cost: 285.00,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Faucet Aerator Set",
      description: "Assorted faucet aerators for water conservation",
      category: "Faucet Parts",
      quantity: 150,
      minQuantity: 30,
      cost: 4.99,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
    {
      id: crypto.randomUUID(),
      name: "Tankless Water Heater",
      description: "Electric tankless water heater 18kW",
      category: "Water Heaters",
      quantity: 8,
      minQuantity: 2,
      cost: 485.00,
      stockMovements: [],
      lastUpdated: new Date().toISOString(),
    },
  ];

  // Add sample data to storage
  sampleVendors.forEach(vendor => storage.addVendor(vendor));
  sampleCustomers.forEach(customer => storage.addCustomer(customer));
  sampleProducts.forEach(product => storage.addInventoryItem(product));

  // Sample Sales Data
  const sampleSales = [
    {
      id: crypto.randomUUID(),
      customerId: sampleCustomers[0].id,
      date: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
      dueDate: new Date(Date.now() + 23 * 24 * 60 * 60 * 1000).toISOString(),
      items: [
        { id: crypto.randomUUID(), productId: sampleProducts[0].id, quantity: 5, unitPrice: 45.50, subtotal: 261.13 },
        { id: crypto.randomUUID(), productId: sampleProducts[2].id, quantity: 2, unitPrice: 89.99, subtotal: 206.98 }
      ],
      total: 468.61,
      status: 'completed' as const,
      paymentStatus: 'paid' as const,
      paymentMethod: 'cash',
      notes: 'Emergency plumbing repair for office building'
    },
    {
      id: crypto.randomUUID(),
      customerId: sampleCustomers[1].id,
      date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
      dueDate: new Date(Date.now() + 27 * 24 * 60 * 60 * 1000).toISOString(),
      items: [
        { id: crypto.randomUUID(), productId: sampleProducts[4].id, quantity: 1, unitPrice: 185.00, subtotal: 212.75 },
        { id: crypto.randomUUID(), productId: sampleProducts[7].id, quantity: 1, unitPrice: 78.50, subtotal: 90.28 }
      ],
      total: 303.03,
      status: 'completed' as const,
      paymentStatus: 'paid' as const,
      paymentMethod: 'credit_card',
      notes: 'Kitchen renovation supplies'
    },
    {
      id: crypto.randomUUID(),
      customerId: sampleCustomers[2].id,
      date: new Date().toISOString(),
      dueDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
      items: [
        { id: crypto.randomUUID(), productId: sampleProducts[11].id, quantity: 2, unitPrice: 125.00, subtotal: 287.50 },
        { id: crypto.randomUUID(), productId: sampleProducts[18].id, quantity: 1, unitPrice: 189.99, subtotal: 218.49 }
      ],
      total: 488.74,
      status: 'pending' as const,
      paymentStatus: 'unpaid' as const,
      paymentMethod: 'bank_transfer',
      notes: 'Office building maintenance order'
    }
  ];

  // Add sample sales to storage
  sampleSales.forEach(sale => storage.addSale(sale));

  console.log("Sample data seeded successfully");
};